export const APP_LOAD = 'APP_LOAD';
export const CRASHREPORT_CHANGED = 'CRASHREPORT_CHANGED';
export const CRASHREPORT_UPLOAD = 'CRASHREPORT_UPLOAD';
export const CRASHREPORT_CONVERT_ERROR = 'CRASHREPORT_CONVERT_ERROR';
export const CRASHREPORT_RESET = 'CRASHREPORT_RESET';
export const SYMBOLICATED_CRASHREPORT = 'SYMBOLICATED_CRASHREPORT';

export default { APP_LOAD, CRASHREPORT_CHANGED, CRASHREPORT_UPLOAD, SYMBOLICATED_CRASHREPORT };
