export const APP_LOAD = 'APP_LOAD';
export const CRASHREPORT_CHANGED = 'CRASHREPORT_CHANGED';
export const CRASHREPORT_UPLOAD = 'CRASHREPORT_UPLOAD';
export const SYMBOLICATED_CRASHREPORT = 'SYMBOLICATED_CRASHREPORT';

export default { APP_LOAD, CRASHREPORT_CHANGED, CRASHREPORT_UPLOAD, SYMBOLICATED_CRASHREPORT };
