export const APP_LOAD = 'APP_LOAD';
export const UPDATE_CODE = 'UPDATE_CODE';
export const SYMBOLICATED_CRASHREPORT = 'SYMBOLICATED_CRASHREPORT';

export default { APP_LOAD, UPDATE_CODE, SYMBOLICATED_CRASHREPORT };
